config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'tops#index'    

  get 'answers/index'
  get 'answers/new'
  
  resources :stockplains
  resources :prefs
  resources :genders
  resources :jobs
  resources :ages
  
  resources :answers

  resources :tops

  resources :forstocks
  
end

app/models/age.rb
class Age < ApplicationRecord
end

app/models/answer.rb
class Answer < ApplicationRecord

  has_one :pref
  has_one :gender
  has_one :job
  has_one :age
  has_one :housing
  has_one :stockplain
  

    # Answer.allで取得するときに、レコード作成日の降順で取得
    default_scope -> { order(created_at: :desc) }
  
    # create前にset_idメソッドを呼出す
    before_create :set_id
  
    private
      def set_id
        # id未設定、または、すでに同じidのレコードが存在する場合はループする
        while self.id.blank? || Answer.find_by(id: self.id).present? do
          # ランダムな20文字をidに設定し、whileの条件検証に戻る
          self.id = SecureRandom.alphanumeric(20)
        end
      end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gender.rb
class Gender < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/pref.rb
class Pref < ApplicationRecord
end

app/models/stockplain.rb
class Stockplain < ApplicationRecord
end

app/controllers/ages_controller.rb
class AgesController < ApplicationController

    def index
        @ages = Age.all
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

    def index
        @jobs = Job.all
    end

end

app/controllers/prefs_controller.rb
class PrefsController < ApplicationController

    def index
        @prefs = Pref.all
    end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

    def index
        @answers = Answer.all
        @counts = Answer.count
    end

end

app/helpers/ages_helper.rb
module AgesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def default_meta_tags
        {
          site: 'sakuSAKU備蓄チェック',
          title: 'sakuSAkU備蓄チェック||ご自宅の防災備蓄をカンタンにチェックできるwebアプリです。',
          reverse: true,
          separator: '|',
          description: 'sakuSAKU備蓄チェックは、万一の非常時用にご家庭の防災備蓄をお手軽にチェックできます。「何を備蓄すれば良いか分からない方」や「家族で備蓄を話し合うきっかけが欲しい方」におすすめです。最短3分程度で終わるので空いた時間でカンタンにチェックできます。是非、ご利用ください。',
          keywords: '地震,台風,備蓄,チェック,保存食',
          canonical: request.original_url,
          noindex: ! Rails.env.production?,
          icon: [
            { href: image_url('favicon.ico') },
            { href: image_url('icon.png'), rel: 'apple-touch-icon-180x180.png', sizes: '180x180', type: 'image/png' },
          ],
          og: {
            site_name: 'sakuSAKU備蓄チェック',
            title: :title,
            description: 'sakuSAKU備蓄チェックは、万一の非常時用にご家庭の防災備蓄をお手軽にチェックできます。「何を備蓄すれば良いか分からない方」や「家族で備蓄を話し合うきっかけが欲しい方」におすすめです。',
            type: 'website',
            url: request.original_url,
            image: image_url('ogp.png'),
            locale: 'ja_JP',
          },
        #   twitter: {
        #     card: 'summary_large_image',
        #     site: '@ツイッターのアカウント名',
        #   }
        #   fb: {
        #     app_id: '自身のfacebookのapplication ID'
        #   }
        }
      end

      
end

app/helpers/forstocks_helper.rb
module ForstocksHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/prefs_helper.rb
module PrefsHelper
end

app/helpers/stockplains_helper.rb
module StockplainsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>sakuSAkU備蓄チェック||ご自宅の防災備蓄をカンタンにチェックできるwebアプリです。</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="apple-touch-icon" type="image/png" href="/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="/icon-192x192.png">

    <%= analytics_init if Rails.env.production? %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.4/css/all.css">

  </head>

  <body>


  
    <header class="headerBox sticky-top">
      <div class="navBox w-100 py-2 pr-3 text-right navBoxBC">
          <div class="navList text-center" id="nav">
              <ul class="w-100 m-0">
                <%= link_to 'Top', root_path ,class:"headerDropdownTitle mx-3"%>
                <%= link_to '備蓄をチェックする', new_answer_path ,class:"headerDropdownTitle mx-3 bg-danger p-2"%>
                <%= link_to '回答一覧を見る', answers_path ,class:"headerDropdownTitle mx-3"%>
                <%# <%= link_to '備蓄アイテムの準備', forstocks_path, class: 'headerDropdownTitle mx-3' %> %>
              </ul> 
          </div>
      </div>
    </header>

    <%= yield %>
    <div class="footer sticky-bottom">
              <div class="navList text-center" id="nav">
              <ul class="w-100 m-0">
                <%= link_to '出典について', root_path(anchor: 'referenceInfo'), class: 'headerDropdownTitle mx-1' %>
                <%= link_to '利用規約', root_path(anchor: 'termsOfUse'), class: 'headerDropdownTitle mx-1' %>
                <%= link_to 'プライバシーポリシー', root_path(anchor: 'privacyPolicy'), class: 'headerDropdownTitle mx-1' %>
                <%= link_to '運営者情報', root_path(anchor: 'aboutUs'),class:"headerDropdownTitle mx-1"%>
              </ul> 
          </div>
      <div class="mt-1 text-center">
        <p>&copy; 2019-<script>document.write(new Date().getFullYear());</script> sakuSAkU備蓄チェック運営</p>
      </div>
    </div>
      <div id="page_top"><a href="#"></a></div>

  </body>
</html>